---
**Created on** *Thu Oct 03 06:29:02 2025*  
**@author**: **Chaitanya.M, DVR and Dr. HS Mic College, Kanchikacharla**

[**GitHub Repository**](https://github.com/chaitanyamokkapati/MIC-ECE-MACHINE-LEARNING-LAB/tree/main/MACHINE%20LEARNING/LAB%20ACTIVITIES/LAB%20ACTIVITY%207)

---


# Lab Activity 7: **Build an Artificial Neural Network by implementing the Back propagation algorithm and test the same using appropriate data sets.**

---
## Objective

> The objective of this notebook is to **understand and implement** the *Backpropagation Algorithm* in an Artificial Neural Network (ANN) and test its performance using an appropriate dataset.

1. **Understand Neural Networks**
   - Learn the basic structure and functioning of neural networks.

2. **Implement Backpropagation**
   - Gain hands-on experience in implementing the *backpropagation algorithm* for training a neural network.

3. **Data Preprocessing**
   - Learn how to **normalize** input and output data for better performance.

4. **Model Training**
   - Train the model and observe how **weights and biases** are adjusted to minimize error.

5. **Evaluate Performance**
   - Test the trained model and evaluate its accuracy using metrics like *Mean Squared Error (MSE)*.

6. **Experiment with Hyperparameters**
   - Explore how changes in **hyperparameters** affect the model's performance.
  
---

### Import Necessary Libraries

In [1]:
import numpy as np

### 2. Prepare the Dataset

In [2]:
# Step 1: Prepare the Data
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)  # Input: [sleep, study hours]
y = np.array(([92], [86], [89]), dtype=float)  # Output: Percentage scores

# Normalize the data (feature scaling)
X = X / np.amax(X, axis=0)  # Normalize the input data to the range 0-1
y = y / 100  # Normalize the output (percentage) between 0 and 1

# Print the normalized data
print("Normalized Input Data (X):")
print(X)
print("\nNormalized Output Data (y):")
print(y)

Normalized Input Data (X):
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Normalized Output Data (y):
[[0.92]
 [0.86]
 [0.89]]


### 3. Define Sigmoid Function and Its Derivative

In [3]:
# Step 2: Define the Sigmoid Activation Function and its Derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def derivatives_sigmoid(x):
    return x * (1 - x)

### 4. Initialize Parameters

In [4]:
# Step 3: Initialize Variables
epoch = 7000  # Number of training iterations (epochs)
lr = 0.1  # Learning rate
inputlayer_neurons = 2  # Number of features in the dataset (sleep and study hours)
hiddenlayer_neurons = 3  # Number of neurons in the hidden layer
output_neurons = 1  # Output neuron (percentage)

# Initialize weights and biases
wh = np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons))  # Weights for the hidden layer
bh = np.random.uniform(size=(1, hiddenlayer_neurons))  # Bias for the hidden layer
wout = np.random.uniform(size=(hiddenlayer_neurons, output_neurons))  # Weights for the output layer
bout = np.random.uniform(size=(1, output_neurons))  # Bias for the output layer

# Print the initial weights and biases
print("Initial Weights and Biases:")
print("Hidden Layer Weights (wh):", wh)
print("Hidden Layer Biases (bh):", bh)
print("Output Layer Weights (wout):", wout)
print("Output Layer Biases (bout):", bout)

Initial Weights and Biases:
Hidden Layer Weights (wh): [[0.35989388 0.71659598 0.64170643]
 [0.47133242 0.65676361 0.06833671]]
Hidden Layer Biases (bh): [[0.35378989 0.63880291 0.0408965 ]]
Output Layer Weights (wout): [[0.93121904]
 [0.91535343]
 [0.53574644]]
Output Layer Biases (bout): [[0.31753841]]


### 5. Training the Network (Forward and Backpropagation)

In [5]:
# Step 4: Train the Neural Network
for i in range(epoch):
    # Forward Propagation
    hinp1 = np.dot(X, wh)  # Linear combination of input and weights (hidden layer input)
    hinp = hinp1 + bh  # Adding bias to hidden layer input
    hlayer_act = sigmoid(hinp)  # Apply sigmoid activation function to hidden layer
    
    outinp1 = np.dot(hlayer_act, wout)  # Linear combination of hidden layer output and output weights
    outinp = outinp1 + bout  # Adding bias to output layer input
    output = sigmoid(outinp)  # Apply sigmoid activation function to output layer
    
    # Backpropagation (Updating Weights and Biases)
    EO = y - output  # Error at the output layer
    outgrad = derivatives_sigmoid(output)  # Gradient of the output layer
    d_output = EO * outgrad  # Error gradient of output layer
    
    EH = d_output.dot(wout.T)  # Error at the hidden layer
    hiddengrad = derivatives_sigmoid(hlayer_act)  # Gradient of the hidden layer
    d_hiddenlayer = EH * hiddengrad  # Error gradient of the hidden layer
    
    # Update the weights and biases
    wout += hlayer_act.T.dot(d_output) * lr  # Update output layer weights
    bout += np.sum(d_output, axis=0, keepdims=True) * lr  # Update output layer bias
    wh += X.T.dot(d_hiddenlayer) * lr  # Update hidden layer weights
    bh += np.sum(d_hiddenlayer, axis=0, keepdims=True) * lr  # Update hidden layer bias

    if i % 1000 == 0:  # Print error every 1000 epochs
        mse = np.mean((y - output) ** 2)  # Calculate Mean Squared Error (MSE)
        print(f"Epoch {i}, MSE: {mse}")

Epoch 0, MSE: 0.00033466670528857533
Epoch 1000, MSE: 0.0003292027858906191
Epoch 2000, MSE: 0.0003244026468271401
Epoch 3000, MSE: 0.00031964544045554635
Epoch 4000, MSE: 0.00031492954306642563
Epoch 5000, MSE: 0.0003102535651317531
Epoch 6000, MSE: 0.0003056163292936562


### 6. Test the Model

In [6]:
# Step 5: Test the Model (Evaluate Performance)
print("\nTraining Complete\n")

# Test Data (New input for prediction)
test_input = np.array(([4, 8], [2, 7]), dtype=float)  # Example test data (new sleep and study hours)
test_input = test_input / np.amax(test_input, axis=0)  # Normalize the test data

# Perform forward propagation with the trained weights
hinp_test = np.dot(test_input, wh)  # Input to hidden layer
hinp_test = hinp_test + bh  # Add bias to hidden layer input
hlayer_act_test = sigmoid(hinp_test)  # Apply sigmoid activation to hidden layer

outinp_test = np.dot(hlayer_act_test, wout)  # Input to output layer
outinp_test = outinp_test + bout  # Add bias to output layer input
output_test = sigmoid(outinp_test)  # Apply sigmoid activation to output layer

print("Predicted Output for Test Data:")
print(output_test * 100)  # Convert back to percentage



Training Complete

Predicted Output for Test Data:
[[90.25621979]
 [88.90420361]]


### 7. Performance Evaluation

In [7]:
# Step 6: Performance Evaluation (Mean Squared Error)
mse = np.mean((y - output) ** 2)  # Calculate Mean Squared Error (MSE)
print("\nMean Squared Error on training data:", mse)


Mean Squared Error on training data: 0.0003010214310793555
